---
- name: Configure the Docker APT key
  apt_key: url=https://get.docker.io/gpg
           keyserver=p80.pool.sks-keyservers.net
           id=58118E89F3A912897C070ADBF76221572C52609D
           state=present

- name: Configure the Docker APT repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main"
                  state=present

- name: Install Docker
  apt: pkg=docker-engine={{ docker_version }} state=present

- name: Configure Docker
  template: src=docker.j2 dest=/etc/default/docker
  notify:
    - Restart Docker

- name: Install Docker API client for Python
  pip: name=docker-py
       version={{ docker_py_version }}
       state=present
